[package]
name = "tdmcli"
version = "0.0.1"
edition = "2021"

[dependencies]
rayon = "1.7"
indicatif = "0.17"
walkdir = "2.3"
dirs = "5.0"
reqwest = { version = "0.11", features = ["blocking"] }
base64 = "0.21"
globset = "0.4"